### PR TITLE
Many fixes

### PR DESCRIPTION
**Pull request by ghost**
Not yet ready for prime-time, but these commits resolve enough errors that the uncommented tests are now passing.

### CODE REVIEW

**Comment by ghost** [comment]
All tests have been uncommented, revised, and made to pass.

**Comment by tcoulter** [comment]
@ryepdx I did not see this when you posted it! Checking it out now.

**Comment by tcoulter** [comment]
@ryepdx Is it important to you to be able to use Ethersim as a library? Personally I think it has very limited usefulness, and it mucks up the manager code quite a bit. 

As far as the other features, here's what I think you added. Can you tell me why these features are important to you? 
1. Configurable gas limit
2. Overridable logging functionality
3. On first glance it looks like you removed the balance from the default accounts. Why? 

FYI: EthereumJS will be consuming my version of EtherSim to create their own ethereumjs-testrpc project. Look for updates to this over there.

**Comment by tcoulter** [comment]
Project has moved to: https://github.com/ethereumjs/testrpc

**Comment by tcoulter** [comment]
@ryepdx I didn't say it directly, but I'd _love_ to include your changes once I understand the motivations. That said, over at ethereumjs/testrpc, I've made a few changes which will likely conflict:
1. I've defaulted the port back to 8545, like consensys/eth-testrpc and other Ethereum clients.
2. I've removed all the tests. In general I know this is "bad", but I think they could be rewritten in a much better way and without talking directly to the manager (this is an RPC client after all; let's use the RPC). 

Let me know if this causes any headache. Still, would very much like to include your changes. Thanks again!

**Comment by kumavis** [comment]
@tcoulter library means you can explore other transports, such as IPC
it can be a library and a cli at the same time very easily

**Comment by tcoulter** [comment]
@kumavis I think Iuri's original intention was to use Ethersim directly as a web3 provider, which has limited benefit. I have trouble thinking of a good use case for that, but could be convinced if one pops up.

**Comment by ghost** [comment]
@tcoulter 

Dapple needs a VM for running its unit tests. EtherSim is attractive because it provides a Provider that can be passed directly to the Web3 class. This simplified things for me because it meant I could use the same code for talking to the VM and for talking to a JSON-RPC client.

In general one wants as much control over the execution environment when testing as possible. In particular, the gas limit as originally set was too low to allow for Test contract execution. As I expected simply raising the hard-coded limit would have put others in the same situation further down the road, I opted to make it configurable.

The overridable logging was important because it allowed us to use EtherSim as a library without having our tool's output interpolated with EtherSim's. I suppose using a package like [mute](https://www.npmjs.com/package/mute) would have also been an option. But allowing users to choose where to direct logging output seemed like a better design choice.

I chose to remove the account default balance because any default balance amount would ultimately be an arbitrary decision on my part, and arguably counterintuitive. In any other context, new accounts don't instantiate with a balance above zero. More importantly, this forces keeping the knowledge about how much is in the test account out of the guts of EtherSim, where developers can't guarantee the number won't change anyway, and into the test that's using EtherSim.

Finally, I don't think it's a good idea to remove the unit tests. Yeah, having EtherSim used as a library might be out of scope, and I respect that, but your components are going to have to interact with each other on their way to responding to user requests. I've never personally regretted having the behavior of my components well-defined and tested, and I have many times regretted _not_ having it so.

**Comment by tcoulter** [comment]
Responding to each of  your paragraphs, as bullets:
- I can see how that's attractive. Truffle for example takes a slightly different approach to its relationship with Ethereum clients. Running your automated tests against geth, for instance, is an important part of the deployment and testing process and so doesn't limit your tests to a specific client. I'd think hardcoding Ethersim as a provider prevents some avenues for testing, but I can see how it boosts ease of use. After talking to @kumavis, ethereumjs-testrpc will definitely structure the code in such a way that allows for this case. (Aside: Without the provider, you can get away with starting Ethersim in a child process, although it's only slightly less elegant.)
- The gas limit was set at the maximum allowable to Ethereum: 3141592. 
  
  > the gas limit as originally set was too low to allow for Test contract execution.
  
  You won't be able to deploy a contract or perform a transaction on a real Ethereum client if you use more gas than that. I understand it's for testing, but you run the risk of setting improper expectations that a certain developer's contract or transaction will go through (just a fair warning). That said, I'm all for making it configurable, especially for setting it downward.  
- Overridable logging. Sounds great. 
- If you remove the default balances, how does any account have any balance enough to perform a transaction on the network? Or did you just remove it for new accounts aside from the defaults? Having default balances is very important to ethereumjs-testrpc's main use case, so I'd like to leave that in. I'd be very open to making the balance configurable for any non-default accounts that get created after boot up. What are your thoughts there? Though I can see that in your context the scope of ethereumjs-testrpc is only for automated tests, but I'd like to maintain the account/client relationship held by other Ethereum clients where the client manages a set of accounts, and those accounts have balances. Since there's no mining within ethereumjs-testrpc, a balance has to come from somewhere and so there needs to be at least one (if not many) accounts that have a balance by default.
- Regarding tests: First and foremost, tests need to be in there. My decision to remove them was simply transitionary because a) they didn't work (except on your branch, which has significant changes), and b) I'm not sure if I trusted them. Tests -- whether the same ones, or new ones -- will make their way back in and I agree they're very important. I'm coming around to the manager interface by the way (async only), but need to think if any restructuring needs to happen beforehand.

Cheers! Thanks for the response.

**Comment by tcoulter** [comment]
Note, just in case you're reading this via email: Made a significant edit to the paragraph about balances. Cheers!

**Comment by ghost** [comment]
- Interfacing with EtherSim via JSON-RPC would certainly work, and I'd be happy to change Dapple's approach on that.
- The current Ethereum gas limit isn't the maximum allowable, really. It's technically the floor, as I understand it. I do see your point, though. Having the default set there makes sense. But really, for test contracts it's necessary to raise the gas limit. They need to run to enable development to continue, and they're never going to actually be deployed so the gas limit doesn't matter. One of the ideas we're kicking around in Dapple is extending the EVM to allow test contracts to change the gas limit during execution, which would provide a work-around and also reduce the distance between the information regarding the gas limit and the code to which that information is most relevant. Might still be nice to allow overriding the gas limit globally as well, but that could be done as a CLI argument or RPC call instead.
- I added a function to allow setting account balances, so code that requires a balance in an account can set whatever balance it needs. Setting the account balance to the maximum wasn't working well because it resulted in an integer overflow if anything got sent to the address. (Side note: shouldn't transactions that cause integer overflows fail? The behavior I observed was simply that the value wrapped around and resulted in a low balance in the account.) I like the idea of having balances be configurable. I don't think having default accounts and magic values is the best idea, just because I tend to the of the opinion that "explicit is better than implicit." I'm a Pythonista at heart. But at the very least, it should be possible to spin up something without any accounts already defined and with zero balances in the accounts I create. Default behavior can be whatever you want it to be, but I want the option to override it.
- Okay, thanks for clarifying. I agree with that reasoning, given that we're re-negotiating interfaces here and the tests define the interfaces.

**Comment by tcoulter** [comment]
- I've come around, and adding a better provider interface that goes through the same pipes as the server (i.e., instead of opening two interfaces: RPC requests and manager.xyz). I'm not finished yet, but would love to get your opinion on it once I'm finished.
- I thought 3141592 was the ceiling? That's the block gas limit, and you'll have a hard time finding a node that will run your transaction if, say, your contract gets close to that line (aside: it took hours to deploy the dapp store because we had single transactions that nearly filled up a whole block, so nodes would prioritize smaller transactions and leave out mine because it meant more transaction fees). 
- Will definitely make the default configurable. Good points.
- Writing tests now. I've copied yours and rewriting / adding some. Mostly it consists of making sync calls async. Expect this and the provider interface in days.

**Comment by tcoulter** [comment]
PS: Thanks for your feedback. Appreciate it.

**Comment by kumavis** [comment]
ps: love you guys :smile_cat:

**Comment by tcoulter** [comment]
@ryepdx @kumavis Would love for both of you to take a look at this. It doesn't cover all your concerns (yet), but a few at least. Would love to know how this fits into what you already have. https://github.com/ethereumjs/testrpc/pull/4

**Comment by tcoulter** [comment]
Perhaps we can write issue tickets for the remaining features within the ethereumjs/testrpc project.

**Comment by ghost** [comment]
Sorry for dropping off. Was slammed the last couple weeks and am now catching up on my communications backlog.

Yeah, writing tickets sounds good. Dapple will continue using my fork for now, but we'll transition to ethereumjs/testrpc as soon as we can.

**Pull request closed without merging**
